#ifndef OPENGL_FUNCTION
#define OPENGL_FUNCTION(type, name)
#endif

#if defined(_WIN32)
OPENGL_FUNCTION(PFNGLACTIVETEXTUREPROC           , glActiveTexture);
#endif

OPENGL_FUNCTION(PFNGLISPROGRAMPROC               , glIsProgram);
OPENGL_FUNCTION(PFNGLISSHADERPROC                , glIsShader);
OPENGL_FUNCTION(PFNGLLINKPROGRAMPROC             , glLinkProgram);
OPENGL_FUNCTION(PFNGLSHADERSOURCEPROC            , glShaderSource);
OPENGL_FUNCTION(PFNGLUSEPROGRAMPROC              , glUseProgram);
OPENGL_FUNCTION(PFNGLGETPROGRAMIVPROC            , glGetProgramiv);
OPENGL_FUNCTION(PFNGLGETPROGRAMINFOLOGPROC       , glGetProgramInfoLog);
OPENGL_FUNCTION(PFNGLGETSHADERIVPROC             , glGetShaderiv);
OPENGL_FUNCTION(PFNGLGETSHADERINFOLOGPROC        , glGetShaderInfoLog);
OPENGL_FUNCTION(PFNGLCREATEPROGRAMPROC           , glCreateProgram);
OPENGL_FUNCTION(PFNGLCREATESHADERPROC            , glCreateShader);
OPENGL_FUNCTION(PFNGLCOMPILESHADERPROC           , glCompileShader);
OPENGL_FUNCTION(PFNGLATTACHSHADERPROC            , glAttachShader);
OPENGL_FUNCTION(PFNGLDELETEPROGRAMPROC           , glDeleteProgram);
OPENGL_FUNCTION(PFNGLDELETESHADERPROC            , glDeleteShader);
OPENGL_FUNCTION(PFNGLGENBUFFERSPROC              , glGenBuffers);
OPENGL_FUNCTION(PFNGLBINDBUFFERPROC              , glBindBuffer);
OPENGL_FUNCTION(PFNGLMAPBUFFERPROC               , glMapBuffer);
OPENGL_FUNCTION(PFNGLUNMAPBUFFERPROC             , glUnmapBuffer);
OPENGL_FUNCTION(PFNGLBUFFERDATAPROC              , glBufferData);
OPENGL_FUNCTION(PFNGLDELETEBUFFERSPROC           , glDeleteBuffers);
OPENGL_FUNCTION(PFNGLENABLEVERTEXATTRIBARRAYPROC , glEnableVertexAttribArray);
OPENGL_FUNCTION(PFNGLDISABLEVERTEXATTRIBARRAYPROC, glDisableVertexAttribArray);
OPENGL_FUNCTION(PFNGLVERTEXATTRIBPOINTERPROC     , glVertexAttribPointer);
OPENGL_FUNCTION(PFNGLGENVERTEXARRAYSPROC         , glGenVertexArrays);
OPENGL_FUNCTION(PFNGLBINDVERTEXARRAYPROC         , glBindVertexArray);
OPENGL_FUNCTION(PFNGLDELETEVERTEXARRAYSPROC      , glDeleteVertexArrays);
OPENGL_FUNCTION(PFNGLTEXSTORAGE2DPROC            , glTexStorage2D);

#undef OPENGL_FUNCTION
